import { useState } from 'react'

import Head from 'next/head'
import Featured from '../components/Featured'
import PizzaList from '../components/PizzaList'
import styles from '../styles/sass/Home.module.scss'
import axios from 'axios'
import AddButton from '../components/AddButton'
import Add from '../components/Add'

export default function Home( { pizzaList, admin } ) {
  const[ close, setClose ] = useState( true );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      {
        admin && <AddButton setClose={ setClose } />
      }
      <PizzaList pizzaList = { pizzaList }  />
      { !close && <Add setClose={ setClose }  /> }
    </div>
  )
}


export const getServerSideProps = async ( ctx ) => {

  const myCookies = ctx.req?.cookies || '';
  let admin = false;

  if( myCookies.token === process.env.TOKEN ) {
    admin = true
  }
  const res = await axios.get('http://localhost:3000/api/products');

  return {
    props: {
      pizzaList: res.data,
      admin
    }
  }
}
